<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>
    <ItemGroup>

        <PackageReference Include="Microsoft.AspNetCore.TestHost" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />

        <PackageReference Include="xunit" />

        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime;build;native;contentfiles;analyzers;buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime;build;native;contentfiles;analyzers;buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>

        <ProjectReference Include="..\..\src\Gateway.OpenTelemetry.Core\Gateway.OpenTelemetry.Core.csproj" />

        <ProjectReference Include="..\..\src\Gateway.OpenTelemetry.AspNetCore\Gateway.OpenTelemetry.AspNetCore.csproj" />

        <ProjectReference Include="..\..\src\Gateway.OpenTelemetry.Yarp\Gateway.OpenTelemetry.Yarp.csproj" />

        <ProjectReference Include="..\Gateway.OpenTelemetry.IntegrationHost\Gateway.OpenTelemetry.IntegrationHost.csproj" />

    </ItemGroup>

</Project>