<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <TargetFramework>net10.0</TargetFramework>

        <PackageId>Gateway.OpenTelemetry.Core</PackageId>

        <Title>Gateway.OpenTelemetry.Core</Title>

        <Description>
            Core abstractions, constants and shared infrastructure for Gateway.OpenTelemetry.
        </Description>

        <Authors>Booviper</Authors>

        <Company>Booviper</Company>

        <PackageTags>
            opentelemetry;gateway;observability;tracing
        </PackageTags>

        <RepositoryUrl>
            https://github.com/booviperza/Gateway.OpenTelemetry
        </RepositoryUrl>

        <RepositoryType>git</RepositoryType>

        <PackageProjectUrl>
            https://github.com/booviperza/Gateway.OpenTelemetry
        </PackageProjectUrl>

        <PackageReadmeFile>README.md</PackageReadmeFile>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageIcon>icon.png</PackageIcon>

    </PropertyGroup>

    <ItemGroup>

        <None Include="..\..\README.md" Pack="true" PackagePath="\" />

        <None Include="..\..\icon.png" Pack="true" PackagePath="\" />

    </ItemGroup>

</Project>