<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Gateway.OpenTelemetry.Core\Gateway.OpenTelemetry.Core.csproj" />
        <ProjectReference Include="..\..\src\Gateway.OpenTelemetry.AspNetCore\Gateway.OpenTelemetry.AspNetCore.csproj" />
        <ProjectReference Include="..\..\src\Gateway.OpenTelemetry.Yarp\Gateway.OpenTelemetry.Yarp.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="OpenTelemetry.Exporter.Console" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="Yarp.ReverseProxy" />
    </ItemGroup>

</Project>